### ISSUE TITLE
Run-time Error in your code and Correct answer is below the question

### ISSUE THREAD

**Issue by krishnasai21** [Thomas-George-T/HackerRank-SQL-Challenges-Solutions#10]
### _https://github.com/Thomas-George-T/HackerRank-SQL-Challenges-Solutions/blob/f4b83edbf8de24d34efb1ae02116dfc9c2c78427/Aggregation/Weather%20Observation%20Station%2020.sql#L5_

```
**select 

round(sta.lat_n, 4) 

from station as sta 

where 

(select count(lat_n) from station where lat_n < sta.lat_n) = (select count(lat_n) from station where lat_n > sta.lat_n);**

```

**Comment by Thomas-George-T** [comment]
Hey @krishnasai21, Thanks for bringing this to my notice. 

This solution was working 2 years ago as seen below but I think something has changed since then. 

![image](https://user-images.githubusercontent.com/20851812/119900330-05cdb680-bf62-11eb-96d4-ae079db73a2b.png)


Please raise a pull request with your working solution.

Thanks
